version: '3'
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicleDB
  mailhog:
    image: mailhog/mailhog:latest
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
